version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    groups:
      minor-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

